export interface WorkdaySiteConfig {
  label: string;
  host: string;
  tenant: string;
  site: string;
}

export interface IcimsSiteConfig {
  label: string;
  host: string;
}

// Public board identifiers only. No API keys or private URLs belong here.
export const defaultLeverCompanies = [
  'activecampaign',
  'AIFund',
  'BDG',
  'alice-bob',
  'aofl',
  'aquabyte',
  'arrivelogistics',
  'autofi',
  'binance',
  'certik',
  'cfsenergy',
  'commoncause',
  'cred',
  'dnb',
  'enable',
  'fiscalnote',
  'floqast',
  'girlswhocode',
  'gohighlevel',
  'grantstreet',
  'guardsquare',
  'heetch',
  'hivemind-capital',
  'houzz',
  'hypersonica-prod',
  'includedhealth',
  'influ2',
  'intropic',
  'jobgether',
  'kitware',
  'loadsmart',
  'lyrahealth',
  'meesho',
  'metlife',
  'mistral',
  'mujininc',
  'muttdata',
  'neon',
  'netomi',
  'palantir',
  'paytm',
  'peerspace',
  'planner5d',
  'plusgrade',
  'ro',
  'sambatv',
  'shieldai',
  'spotify',
  'sprymethods',
  'teller',
  'tri',
  'veeva',
  'wealthfront',
  'zartis',
  'zoox',
  '15five',
  'accesssoftek',
  'achievers',
  'agiloft',
  'aircall',
  'anyscale',
  'aogarciaagency',
  'arcteryx.com',
  'bhvr',
  'blablacar',
  'blencorp',
  'bluelightconsulting',
  'bounteous',
  'deepgenomics',
  'dlocal',
  'economicmodeling',
  'educative',
  'Espresso',
  'galatea-associates',
  'geocomply-2',
  'goodleap',
  'highstreetit',
  'hihello',
  'immuta',
  'immutable',
  'jito.wtf',
  'jobandtalent',
  'kepler',
  'kpmgnz',
  'levelai',
  'leverdemo',
  'lumotive',
  'magnetforensics',
  'marcopolo',
  'matchgroup',
  'mechanicalorchard',
  'metabase',
  'miteksystems-2',
  'myollie',
  'nimblerx',
  'noodle',
  'offchainlabs',
  'outreach',
  'paralleldomain',
  'provectus',
  'quantcast',
  'renofi',
  'serotonin',
  'slangai',
  'sprucesystems',
  'super-com',
  'superside',
  'telesat',
  'thinkahead',
  'thinkingbox',
  'toptal',
  'trustyou',
  'veepee',
  'viabill',
  'voodoo',
  'waabi',
  'waterfall',
  'webfx',
  'weride',
  'whoop',
];

export const defaultGreenhouseBoards = [
  '10xgenomics',
  'accenturefederalservices',
  'adyen',
  'affirm',
  'agwestfarmcredit',
  'airbnb',
  'airtable',
  'alertmedia',
  'algolia',
  'alphasense',
  'altoslabs',
  'amplitude',
  'andurilindustries',
  'anthropic',
  'appfire',
  'appier',
  'applovin',
  'archer',
  'arizeai',
  'asana',
  'astranis',
  'axios',
  'axon',
  'beam',
  'block',
  'bloomreach',
  'boxinc',
  'bracebridgecapital',
  'brex',
  'buzzfeed',
  'calendly',
  'calm',
  'canonical',
  'capco',
  'capitalrx',
  'carrotfertility',
  'cerebral',
  'chime',
  'circleci',
  'civisanalytics',
  'classpass',
  'clear',
  'cloudbeds',
  'cloudflare',
  'cockroachlabs',
  'coinbase',
  'consensys',
  'costar',
  'coursera',
  'databricks',
  'datadog',
  'dbtlabsinc',
  'deepmind',
  'degreed',
  'descript',
  'discord',
  'doordashusa',
  'doximity',
  'dragos',
  'dropbox',
  'duolingo',
  'elastic',
  'elationhealth',
  'elementbiosciences',
  'enterpret',
  'esri',
  'evolutioniq',
  'faire',
  'fairmarkit',
  'fastly',
  'figma',
  'figureai',
  'fingerprint',
  'fireblocks',
  'fivetran',
  'flexport',
  'flohealth',
  'flyzipline',
  'forter',
  'fox',
  'gemini',
  'getwellnetwork',
  'ginkgobioworks',
  'gitlab',
  'gleanwork',
  'godaddy',
  'grafanalabs',
  'graphcore',
  'groww',
  'guardsquare',
  'gusto',
  'gympass',
  'hasbro',
  'hightouch',
  'humaninterest',
  'humeai',
  'ibkr',
  'icapitalnetwork',
  'inceptive',
  'inflectionai',
  'instabase',
  'instacart',
  'instawork',
  'intercom',
  'janestreet',
  'khanacademy',
  'kivaorg',
  'klaviyo',
  'kodiak',
  'komodohealth',
  'konradgroup',
  'labelbox',
  'lattice',
  'launchdarkly',
  'lucidmotors',
  'lyft',
  'machinifyinc',
  'merqube',
  'mochihealth',
  'mongodb',
  'monzo',
  'motional',
  'motive',
  'mozilla',
  'nanit',
  'narvar',
  'natera',
  'navtechnologies',
  'neo4j',
  'netlify',
  'neuralink',
  'newrelic',
  'newsbreak',
  'nextdoor',
  'nubank',
  'nuro',
  'okta',
  'oura',
  'outschool',
  'pagerduty',
  'pallet',
  'paypay',
  'peloton',
  'phonepe',
  'pineparkhealth',
  'pingcap',
  'pinterest',
  'planetlabs',
  'planetscale',
  'point72',
  'postscript',
  'prolific',
  'qualtrics',
  'quince',
  'realchemistry',
  'recidiviz',
  'recordedfuture',
  'reddit',
  'redwoodmaterials',
  'remotecom',
  'ripple',
  'robinhood',
  'roblox',
  'roboforce',
  'rocketlab',
  'roku',
  'rubrik',
  'runpod',
  'samsara',
  'sayari',
  'scaleai',
  'scopely',
  'scout24',
  'securityscorecard',
  'sezzle',
  'shifttechnology',
  'showpad',
  'sigmacomputing',
  'silvus',
  'singlestore',
  'smartbear',
  'smartsheet',
  'snorkelai',
  'sofi',
  'sourcegraph91',
  'spacex',
  'specterops',
  'speechify',
  'stackadapt',
  'stripe',
  'tailscale',
  'taketwo',
  'talkspace',
  'tanium',
  'temporaltechnologies',
  'tenableinc',
  'thenewyorktimes',
  'thinkingmachines',
  'toast',
  'togetherai',
  'torcrobotics',
  'transmarketgroup',
  'trufflesecurity',
  'twilio',
  'twitch',
  'typeform',
  'udemy',
  'underdogfantasy',
  'uniteus',
  'vercel',
  'verisign',
  'verkada',
  'virtu',
  'warp',
  'watershed',
  'waymo',
  'webflow',
  'wikimedia',
  'wonderschool',
  'workato',
  'xai',
  'yugabyte',
  'zscaler',
  'zupinnovation',
  'abbyy',
  'abnormalsecurity',
  'acrisureinnovation',
  'ada18',
  'amarok',
  'amca',
  'apaleo',
  'appian',
  'apptronik',
  'aquaticcapitalmanagement',
  'array',
  'artefact',
  'assemblyai',
  'atoms',
  'automox',
  'axiom',
  'azragames',
  'backblaze',
  'betterment',
  'bicyclehealth',
  'bishopfox',
  'bitpanda',
  'blastpoint',
  'branch',
  'braze',
  'builtin',
  'bvnk',
  'cabify',
  'caribou',
  'carta',
  'caylent',
  'celonis',
  'checkr',
  'civicactions',
  'cloudchamberen',
  'codepath',
  'contentful',
  'contentstack',
  'coreweave',
  'cortica',
  'cresta',
  'cribl',
  'cybereason',
  'dataiku',
  'dept',
  'devrev',
  'dialpad',
  'diligentcorporation',
  'dollarshaveclub',
  'drweng',
  'earnin',
  'ethos',
  'everlaw',
  'everquote',
  'expel',
  'fellow',
  'fetch',
  'figment',
  'fireworksai',
  'five9',
  'flexe',
  'flyziplineur',
  'formic',
  'formlabs',
  'fubotv',
  'fundraiseup',
  'geotab',
  'gomotive',
  'guidepointsecurity',
  'helloalice',
  'highnote',
  'hopskipdrive',
  'ideo',
  'idme',
  'imc',
  'inmobi',
  'inthepocket',
  'isccareers',
  'iterable',
  'ivalua',
  'jetbrains',
  'jobsatphamily',
  'justanswer',
  'justworks',
  'kalshi',
  'karat',
  'ketryx',
  'keystone',
  'later',
  'latitude',
  'leagueinc',
  'legalist',
  'lendingtree',
  'life360',
  'liveperson',
  'locusrobotics',
  'loop',
  'make',
  'marqeta',
  'masterclass',
  'mattermost',
  'melio',
  'mercari',
  'mercury',
  'mixpanel',
  'myfitnesspal',
  'n26',
  'nearform',
  'nebius',
  'newsela',
  'onemedical',
  'opaquesystems',
  'openenergytransition',
  'orca',
  'osano',
  'oscar',
  'ownwell',
  'pairteam',
  'parallellearning',
  'parloa',
  'payoneer',
  'pendo',
  'perpay',
  'polyai',
  'postman',
  'prismatic',
  'proof',
  'proton',
  'purestorage',
  'rackner',
  'radixuniversity',
  'raft',
  'razorpaysoftwareprivatelimited',
  'relativity',
  'rvohealth',
  'saasgroup',
  'saatva',
  'salesloft',
  'samsungresearchamericainternship',
  'scotch',
  'seamlessai',
  'seatgeek',
  'sendbird',
  'shakepay',
  'shein',
  'shipbobinc',
  'shopmonkey',
  'sifthealthcare',
  'siliconranch',
  'sparkfund',
  'spire',
  'squarespace',
  'stabilityai',
  'starburst',
  'Starcloud',
  'stone',
  'stubhubinc',
  'sumup',
  'synthesishealth',
  'taboola',
  'taskrabbit',
  'teampicnic',
  'techstars57',
  'tekion',
  'thealleninstitute',
  'thunes',
  'tigera',
  'tines',
  'transcarent',
  'tripactions',
  'tripadvisor',
  'truework',
  'trustpilot',
  'truveta',
  'twochairs',
  'unity3d',
  'upstart',
  'vaticlabs',
  'vaynermedia',
  'verainstituteofjustice',
  'veriff',
  'verve',
  'vonage',
  'vsco39',
  'wavemm1',
  'wooga',
  'workatbackbase',
  'wrike',
  'wyndlabs',
  'xapo61',
  'yext',
  'yotpo',
  'youcom',
  'zennioptical',
  'ziprecruiter',
  'zocdoc',
];

export const defaultAshbyBoards = [
  '1password',
  'Amplitude',
  'Ashby',
  'abridge',
  'Benchling',
  'beamimpact',
  'Cedar',
  'Clickup',
  'Cognition',
  'Cohere',
  'Confluent',
  'Cursor',
  'datafold',
  'Docker',
  'Elevenlabs',
  'gridcare',
  'Harvey',
  'Headway',
  'hims-and-hers',
  'imprint',
  'Insitro',
  'LangChain',
  'Linear',
  'Mercor',
  'ModernTreasury',
  'Mosaic',
  'n1',
  'Neon',
  'notable',
  'Notion',
  'Nubank',
  'OpenAI',
  'Oso',
  'permitflow',
  'Perplexity',
  'Persona',
  'Plaid',
  'PostHog',
  'prompt',
  'Ramp',
  'replit',
  'revenuebase-inc',
  'Redis',
  'Render',
  'Ridealso',
  'Runway',
  'Sentry',
  'sesame',
  'sierra',
  'Skydio',
  'Snowflake',
  'sola',
  'subsets',
  'Supabase',
  'Synthesia',
  'teamworks',
  'Watershed',
  'Zapier',
  '9fin',
  'attio',
  'baseten',
  'braintrust',
  'clera',
  'Crusoe',
  'decagon',
  'deepgram',
  'drata',
  'eightsleep',
  'everai',
  'firecrawl',
  'handshake',
  'helion',
  'higharc',
  'hopper',
  'juicebox',
  'junipersquare',
  'lavendo',
  'modal',
  'n8n',
  'netgear',
  'oneapp',
  'periodic-labs',
  'primer',
  'reflectionai',
  'revenuecat',
  'rula',
  'sandboxaq',
  'sequence',
  'solink',
  'tessera-labs',
  'truelogic',
  'vanta',
  'vapi',
  'virtahealth',
  'weave',
  'webai',
  'workos',
];

export const defaultSmartRecruitersCompanies = [
  'Abbvie',
  'AIRCommunities',
  'AristaNetworks',
  'AveryDennison',
  'BoschGroup',
  'BuildersFirstsource',
  'CamdenPropertyTrust',
  'Canva',
  'Cencora',
  'DeliveryHero',
  'Dev2',
  'DominoS',
  'Experian',
  'HenrySchein',
  'IronMountain',
  'Jobiak1',
  'Kenvue',
  'KimberlyClark',
  'LiveNationEntertainment',
  'Mosaic',
  'NBCUniversal3',
  'NewRelic',
  'NielsenIQ',
  'NorwegianCruiseLine',
  'Palantir',
  'Pentair',
  'PublicStorage',
  'Resmed',
  'Sandisk',
  'ServiceNow',
  'SmartRecruiters',
  'SOSi1',
  'SynecticsForManagementDecisionsInc',
  'TradeDesk',
  'TredenceAnalytic',
  'Uber',
  'Visa',
  'Wabtec',
  'Wayfair',
  'WesternDigital',
  'Wise',
  'Workato',
  'WynnResorts',
];

export const defaultWorkableAccounts = [
  'boostdraft',
  'devsinc-17',
  'dispel',
  'ellison-institute-of-technology',
  'enable-data',
  'fortanix',
  'huggingface',
  'infotrack-us',
  'middleburycollege',
  'saalex',
  'schoolinks',
  'tetrascience',
  'third-eye-software',
  'uni-systems',
  'xcelirate',
  'keywords-intl1',
  'toloka-ai',
  'mercari',
  'workana-premium',
  'lovebonito',
  'minderacraft',
  'mlabs',
  'starling-bank',
  'covergo',
  'intellecthq',
  'remote-talent-latam',
  'thorlabs',
  'genetec-inc',
  'bayutdubizzle',
  'cloudlinux-1',
  'valsoft-corp',
  'exotec',
  'surglobal',
  'ascendis-pharma',
  'imachines',
  'coldquanta',
  'skeletontech',
  'cloudfactory',
  'datamark-inc',
  'hack-the-box-ltd',
  'sangoma-3',
  'righthookdigital',
  'trexquant',
  'innovaccer-analytics',
  'enroute',
  'deepsource',
  'exoticca',
  'pepperstone',
  'arbor-education-3',
  'openmined',
  'tecsys',
  'deblock',
  'datavisor-jobs',
  'followloop',
  'quandela',
  'rokt',
  'seeq',
  'orfium',
  'quantumloopai',
  'reversinglabs',
  'speexx',
  'kroo',
  'io-global',
  'lunit',
  'modash',
  'leadtech',
  'ensodata',
];

export const defaultRecruiteeCompanies = [
  '1komma5grad',
  'addepto',
  'bizzy',
  'bushburgpropertiesinc',
  'cainwattersassociates',
  'constellr',
  'deepsea',
  'digitalforms',
  'enersee',
  'glpg',
  'hike2',
  'hudsonmanpower',
  'idegogroup',
  'metyisag',
  'natuvion',
  'nodeworthy',
  'nucsai',
  'qualifyzegmbh',
  'resourcefultalentgroup',
  'rewire',
  'riverflex',
  'shortpoint',
  'tiledmediaoperationsbv',
  'trafilea',
  'transperfect',
  'zensai',
  'asksuite',
  'bitfinex',
  'causalens',
  'channable',
  'claranetitalia',
  'comnovogmbh',
  'cornerbancasa',
  'crazygames',
  'distilled',
  'formo',
  'holded',
  'holepunch',
  'huaweicanada',
  'infoprolearning',
  'institutminestelecom',
  'instruqt',
  'mcdugaldsteele',
  'nsiit',
  'opengovernmentproducts',
  'passionfroot',
  'payflows',
  'protectdemocracy',
  'rebogroep',
  'sellsy',
  'tbibankro',
  'variantas',
  'ypto',
  'zeotap',
  'cscfi',
  'kigroup',
  'famly',
  'affidearomania',
  'interbrandsorbico',
  'epilot',
  'legalfly',
  'mrpjobs',
  'cta',
  'tiugotech',
  'intent',
  'hostaway',
  'xneelo',
  'freeday',
  'nacardesign',
  'radishlab',
  'appetiser',
  'greatminds',
  'brainsquare',
  'make',
  'supersummary',
  'emergentsoftware',
  'snapp',
  'teeturtle',
  'machinelearningreply',
  'huuuge',
  'framestore',
  'asmpthk',
  'dransay',
  'tameson',
  'polaroid',
  'artifactsa',
  'attendi',
  'nmbrs',
  'xchange',
  'mgid',
  'climeworks',
  'flextrade',
  'thirdway',
  'allright',
  'anywhereworks',
  'cjbarrymores',
  'novritschtrading',
  'pur',
  'bluelakefineartscamp',
  'properfood',
  'suttons',
  'blackdiamond',
  'constructivedialogue',
  'chgcareers',
];

export const defaultPersonioCompanies = [
  '1komma5grad',
  'adorsys',
  'astrafy',
  'baramundi-software-ag',
  'crealytics',
  'data4life',
  'eraneos',
  'gridx',
  'personio',
  'twaice',
  'xibix-solutions-gmbh',
  'alteos',
  'bigpoint',
  'bitcap',
  'circus',
  'civey-gmbh',
  'contabo',
  'cuculus-gmbh',
  'edgeless-systems',
  'egym',
  'exnaton-ag',
  'friendlycaptcha',
  'gnosis',
  'holidaypirates',
  'liveeo-gmbh',
  'm4c',
  'urbansportsclub',
  'e-mobil-bw-gmbh',
  'meteocontrol',
  'thefemalecompany',
  'intrafind-software-ag',
  'mrge-group-gmbh',
  'super-ai',
  'statworx',
  'chp',
  'hahnair',
  'autarcenergy',
  'epages-gmbh',
  'gesis',
  'jambit-gmbh',
  'giant-swarm',
  'banxware',
  'thinksurance-gmbh',
  'penzilla-gmbh',
  'spread-gmbh',
  'caravelo',
  '1nce',
  'holoplot',
  'praxiseins',
  'semron',
  'coffeecircle',
  'knowisag',
  'lepaya',
  'poellath-rechtsanwaelte',
  'palabra-praxisgruppe-gmbh',
  'adsquare',
  'agentur-medienlabor',
  'ecpmf-sce-mbh',
  'sungrow-emea',
  'recup',
  'koro-handels-gmbh',
  'l21s-gmbh',
  'checkmk-gmbh',
  'rosengarten-gmbh',
  'proveg',
  'autonomous-teaming',
  'syde',
  'tfs',
  'nevis',
  'derichebourg',
  'climedo',
  'instinct3',
  'screeningeagle',
  'envelio',
  'ory',
  'pitch',
  'vodeno',
];

export const defaultIcimsSites: IcimsSiteConfig[] = [
  { label: 'Community Medical Centers', host: 'careers-communitymedical.icims.com' },
  { label: 'iCIMS Idemia', host: 'uscareers-idemia.icims.com' },
  { label: 'IEHP', host: 'careers-iehp.icims.com' },
  { label: 'Mackenzie Investments', host: 'careersen-mackenzieinvestments.icims.com' },
  { label: 'MLS Soccer', host: 'careers-mlssoccer.icims.com' },
  { label: 'Northern Arizona Healthcare', host: 'careers-nahealth.icims.com' },
  { label: 'Prime Healthcare', host: 'careers-primehealthcare.icims.com' },
  { label: 'Providence Health Care', host: 'careers-phc.icims.com' },
  { label: 'Riverside Health', host: 'careers-riversidehealth.icims.com' },
  { label: 'Covenant Health', host: 'careers-covenanthealth.icims.com' },
  { label: 'OSU Physicians', host: 'careers-osuphysicians.icims.com' },
  { label: 'Centric Brands', host: 'careers-centricbrands.icims.com' },
  { label: 'Princeton', host: 'service-princeton.icims.com' },
  { label: 'Utah State', host: 'careers-usu.icims.com' },
  { label: 'Enterprise Mobility', host: 'us-erac.icims.com' },
  { label: 'Western & Southern', host: 'careers-westernsouthern.icims.com' },
  { label: 'Snap-on', host: 'careers-snapon.icims.com' },
  { label: 'Vitamin Shoppe', host: 'retailcareers-vitaminshoppe.icims.com' },
  { label: 'America First Credit Union', host: 'careers-americafirst.icims.com' },
  { label: 'Allied Universal', host: 'corporatecareers-aus.icims.com' },
  { label: 'Bi-Mart', host: 'careers-bimart.icims.com' },
  { label: 'CareCentrix', host: 'careers-carecentrix.icims.com' },
  { label: 'Peraton', host: 'careers-peraton.icims.com' },
  { label: 'Treliant', host: 'careers-treliant.icims.com' },
  { label: 'Metropolitan Water District', host: 'careers-mwdh2o.icims.com' },
  { label: "SOS Children's Villages", host: 'careers-sos-kd.icims.com' },
  { label: 'Dendreon', host: 'careers-dendreon.icims.com' },
  { label: 'Peel Region', host: 'careers-peelregion.icims.com' },
  { label: 'AHMC Healthcare', host: 'careers-ahmchealth.icims.com' },
  { label: 'Good Shepherd Hospice', host: 'careers-goodshepherdhospice.icims.com' },
  { label: 'SFO', host: 'external-flysfo.icims.com' },
  { label: 'Sage Hospitality', host: 'careers-sagehospitality.icims.com' },
  { label: 'WellBe Senior Medical', host: 'careers-wellbeseniormedical.icims.com' },
  { label: 'Orange County Public Schools', host: 'classified-ocps.icims.com' },
  { label: 'Stifel', host: 'careers-stifel.icims.com' },
  { label: 'CoralTree Hospitality', host: 'careers-coraltreehospitality.icims.com' },
  { label: 'Heritage Christian Services', host: 'careers-heritagechristianservices.icims.com' },
  { label: 'Avison Young UK', host: 'careers-avisonyounguk.icims.com' },
  { label: 'symplr', host: 'careers-symplr.icims.com' },
  { label: 'Memphis-Shelby County Schools', host: 'schoolsupportapply-scsk12.icims.com' },
  { label: 'Accion', host: 'jobs-accion.icims.com' },
  { label: 'ATCC', host: 'careers-atcc.icims.com' },
  { label: 'Rambus', host: 'careers-rambus.icims.com' },
  { label: 'Northwood Technical College', host: 'careers-northwoodtechnicalcollege.icims.com' },
  { label: 'SAS', host: 'globalcareers-sas.icims.com' },
  { label: 'Sargent & Lundy', host: 'careers-sargentlundy.icims.com' },
  { label: 'General Dynamics Mission Systems', host: 'careers-gdms.icims.com' },
  { label: 'Expleo Ireland', host: 'expleo-jobs-ie-en.icims.com' },
  { label: 'i3', host: 'careers-i3-corps.icims.com' },
  { label: 'Milton CAT', host: 'careers-miltoncat.icims.com' },
  { label: 'Bassett Healthcare', host: 'learningexperiences-bassett.icims.com' },
  { label: 'HERE Technologies', host: 'careers-here.icims.com' },
  { label: 'ARC Corporation', host: 'careers-arccorp.icims.com' },
  { label: 'NV5', host: 'careers-nv5.icims.com' },
  { label: 'Chenega', host: 'careers-chenega.icims.com' },
  { label: 'Cayuse Holdings', host: 'careers-cayuseholdings.icims.com' },
  { label: 'Gannett Fleming', host: 'careers-gannettfleming.icims.com' },
  { label: 'SSOE', host: 'careers-ssoe.icims.com' },
  { label: 'SRI International', host: 'careers-sri.icims.com' },
];

export const defaultWorkdaySites: WorkdaySiteConfig[] = [
  {
    label: 'Boeing',
    host: 'boeing.wd1.myworkdayjobs.com',
    tenant: 'boeing',
    site: 'EXTERNAL_CAREERS',
  },
  {
    label: 'Adobe',
    host: 'adobe.wd5.myworkdayjobs.com',
    tenant: 'adobe',
    site: 'external_experienced',
  },
  {
    label: 'Austin Community College',
    host: 'austincc.wd1.myworkdayjobs.com',
    tenant: 'austincc',
    site: 'External',
  },
  {
    label: 'City of Austin',
    host: 'austintexas.wd5.myworkdayjobs.com',
    tenant: 'austintexas',
    site: 'COA_Careers',
  },
  {
    label: 'Comcast',
    host: 'comcast.wd5.myworkdayjobs.com',
    tenant: 'comcast',
    site: 'Comcast_Careers',
  },
  {
    label: 'Denver',
    host: 'denver.wd1.myworkdayjobs.com',
    tenant: 'denver',
    site: 'CCD-denver-denvergov-CSC_Jobs-Civil_service_jobs-Police_Jobs-Fire_Jobs',
  },
  {
    label: 'Jefferson County',
    host: 'jefferson.wd5.myworkdayjobs.com',
    tenant: 'jefferson',
    site: 'External',
  },
  {
    label: 'Lowes',
    host: 'lowes.wd5.myworkdayjobs.com',
    tenant: 'lowes',
    site: 'LWS_External_CS',
  },
  {
    label: 'Nevada System CSN',
    host: 'nshe.wd1.myworkdayjobs.com',
    tenant: 'nshe',
    site: 'CSN-External',
  },
  {
    label: 'Ohio State',
    host: 'osu.wd1.myworkdayjobs.com',
    tenant: 'osu',
    site: 'OSUCareers',
  },
  {
    label: 'State of Oklahoma',
    host: 'okgov.wd1.myworkdayjobs.com',
    tenant: 'okgov',
    site: 'okgovjobs',
  },
  {
    label: 'Stevens Institute',
    host: 'stevens.wd5.myworkdayjobs.com',
    tenant: 'stevens',
    site: 'External',
  },
  {
    label: 'Target',
    host: 'target.wd5.myworkdayjobs.com',
    tenant: 'target',
    site: 'targetcareers',
  },
  {
    label: 'Thermo Fisher',
    host: 'thermofisher.wd5.myworkdayjobs.com',
    tenant: 'thermofisher',
    site: 'thermofishercareers',
  },
  {
    label: 'Unum',
    host: 'unum.wd1.myworkdayjobs.com',
    tenant: 'unum',
    site: 'External',
  },
  {
    label: 'University of Arkansas System',
    host: 'uasys.wd5.myworkdayjobs.com',
    tenant: 'uasys',
    site: 'UASYS',
  },
  {
    label: 'University of Nevada Reno',
    host: 'nshe.wd1.myworkdayjobs.com',
    tenant: 'nshe',
    site: 'UNR-external',
  },
  {
    label: 'Vera Whole Health',
    host: 'verawholehealth.wd1.myworkdayjobs.com',
    tenant: 'verawholehealth',
    site: 'External',
  },
  {
    label: 'Washington University',
    host: 'wustl.wd1.myworkdayjobs.com',
    tenant: 'wustl',
    site: 'External',
  },
  {
    label: 'Workday',
    host: 'workday.wd5.myworkdayjobs.com',
    tenant: 'workday',
    site: 'Workday',
  },
  {
    label: 'Yakima County',
    host: 'yakimacounty.wd5.myworkdayjobs.com',
    tenant: 'yakimacounty',
    site: 'YakimaCountyWA',
  },
  {
    label: 'Ontario International Airport',
    host: 'ont.wd5.myworkdayjobs.com',
    tenant: 'ont',
    site: 'External',
  },
  {
    label: 'University of Chicago',
    host: 'uchicago.wd5.myworkdayjobs.com',
    tenant: 'uchicago',
    site: 'External',
  },
  {
    label: 'Intel',
    host: 'intel.wd1.myworkdayjobs.com',
    tenant: 'intel',
    site: 'External',
  },
  {
    label: 'Rockwell Automation',
    host: 'rockwellautomation.wd1.myworkdayjobs.com',
    tenant: 'rockwellautomation',
    site: 'External_Rockwell_Automation',
  },
  {
    label: 'Minnesota State',
    host: 'minnstate.wd115.myworkdayjobs.com',
    tenant: 'minnstate',
    site: 'Minnesota_State_Careers',
  },
  {
    label: 'Morgan Stanley',
    host: 'ms.wd5.myworkdayjobs.com',
    tenant: 'ms',
    site: 'External',
  },
  {
    label: 'Applied Materials',
    host: 'amat.wd1.myworkdayjobs.com',
    tenant: 'amat',
    site: 'External',
  },
  {
    label: 'NVIDIA',
    host: 'nvidia.wd5.myworkdayjobs.com',
    tenant: 'nvidia',
    site: 'NVIDIAExternalCareerSite',
  },
  {
    label: 'Williams',
    host: 'williams.wd5.myworkdayjobs.com',
    tenant: 'williams',
    site: 'External',
  },
  {
    label: 'SOM',
    host: 'som.wd5.myworkdayjobs.com',
    tenant: 'som',
    site: 'External',
  },
  {
    label: 'Wolters Kluwer',
    host: 'wk.wd3.myworkdayjobs.com',
    tenant: 'wk',
    site: 'External',
  },
  {
    label: 'Baltimore City',
    host: 'baltimorecity.wd1.myworkdayjobs.com',
    tenant: 'baltimorecity',
    site: 'External',
  },
  {
    label: 'Embry Riddle',
    host: 'embryriddle.wd1.myworkdayjobs.com',
    tenant: 'embryriddle',
    site: 'External',
  },
  {
    label: 'Analog Devices',
    host: 'analogdevices.wd1.myworkdayjobs.com',
    tenant: 'analogdevices',
    site: 'External',
  },
  {
    label: 'Valmet Field Service',
    host: 'valmet.wd103.myworkdayjobs.com',
    tenant: 'valmet',
    site: 'FieldService',
  },
  {
    label: 'Cloudera',
    host: 'cloudera.wd5.myworkdayjobs.com',
    tenant: 'cloudera',
    site: 'External_Career',
  },
  {
    label: 'University of Louisville',
    host: 'uofl.wd1.myworkdayjobs.com',
    tenant: 'uofl',
    site: 'UofLCareerSite',
  },
  {
    label: 'Palm Beach State',
    host: 'palmbeachstate.wd1.myworkdayjobs.com',
    tenant: 'palmbeachstate',
    site: 'external',
  },
  {
    label: 'Macomb County',
    host: 'macombgov.wd1.myworkdayjobs.com',
    tenant: 'macombgov',
    site: 'External',
  },
  {
    label: 'New School',
    host: 'newschool.wd1.myworkdayjobs.com',
    tenant: 'newschool',
    site: 'External',
  },
  {
    label: 'Discovery Land Company',
    host: 'discoverylandco.wd5.myworkdayjobs.com',
    tenant: 'discoverylandco',
    site: 'DLC',
  },
  {
    label: 'Blue Cross Blue Shield Louisiana',
    host: 'bcbsla.wd1.myworkdayjobs.com',
    tenant: 'bcbsla',
    site: 'External',
  },
  {
    label: 'Boulder Colorado',
    host: 'bouldercolorado.wd1.myworkdayjobs.com',
    tenant: 'bouldercolorado',
    site: 'External',
  },
  {
    label: 'Idaho Power',
    host: 'idahopowercompany.wd1.myworkdayjobs.com',
    tenant: 'idahopowercompany',
    site: 'External',
  },
  {
    label: 'Waukesha County',
    host: 'waukeshacounty.wd12.myworkdayjobs.com',
    tenant: 'waukeshacounty',
    site: 'Careers',
  },
  {
    label: 'Mass General Brigham',
    host: 'massgeneralbrigham.wd1.myworkdayjobs.com',
    tenant: 'massgeneralbrigham',
    site: 'MGBExternal',
  },
  {
    label: 'Kyndryl',
    host: 'kyndryl.wd5.myworkdayjobs.com',
    tenant: 'kyndryl',
    site: 'KyndrylProfessionalCareers',
  },
  {
    label: 'University of Miami',
    host: 'umiami.wd1.myworkdayjobs.com',
    tenant: 'umiami',
    site: 'UMCareerStaff',
  },
  {
    label: 'Cushman Wakefield',
    host: 'cw.wd1.myworkdayjobs.com',
    tenant: 'cw',
    site: 'External',
  },
  {
    label: 'Multnomah County',
    host: 'multco.wd1.myworkdayjobs.com',
    tenant: 'multco',
    site: 'Multco_Jobs',
  },
  {
    label: 'Four Seasons',
    host: 'fourseasons.wd3.myworkdayjobs.com',
    tenant: 'fourseasons',
    site: 'search',
  },
  {
    label: 'Richland WA',
    host: 'cirichlandwa.wd12.myworkdayjobs.com',
    tenant: 'cirichlandwa',
    site: 'COR',
  },
  {
    label: 'University of Rochester',
    host: 'rochester.wd5.myworkdayjobs.com',
    tenant: 'rochester',
    site: 'UR_Staff',
  },
  {
    label: 'Steamboat Springs',
    host: 'steamboatsprings.wd12.myworkdayjobs.com',
    tenant: 'steamboatsprings',
    site: 'External',
  },
  {
    label: 'University of Maryland',
    host: 'umd.wd1.myworkdayjobs.com',
    tenant: 'umd',
    site: 'UMCP',
  },
  {
    label: 'Dallas City Hall',
    host: 'dallascityhall.wd5.myworkdayjobs.com',
    tenant: 'dallascityhall',
    site: 'CODCareers',
  },
  {
    label: 'Prysmian Group',
    host: 'prysmiangroup.wd3.myworkdayjobs.com',
    tenant: 'prysmiangroup',
    site: 'Careers',
  },
  {
    label: 'Rolls Royce',
    host: 'rollsroyce.wd3.myworkdayjobs.com',
    tenant: 'rollsroyce',
    site: 'professional',
  },
  {
    label: 'Iowa State',
    host: 'isu.wd1.myworkdayjobs.com',
    tenant: 'isu',
    site: 'IowaStateJobs',
  },
  {
    label: 'Wonder',
    host: 'wonder.wd1.myworkdayjobs.com',
    tenant: 'wonder',
    site: 'WG',
  },
  {
    label: 'Warner Bros Discovery',
    host: 'warnerbros.wd5.myworkdayjobs.com',
    tenant: 'warnerbros',
    site: 'global',
  },
  {
    label: 'Aritzia',
    host: 'aritzia.wd3.myworkdayjobs.com',
    tenant: 'aritzia',
    site: 'External',
  },
  {
    label: 'Johnson Controls',
    host: 'jci.wd5.myworkdayjobs.com',
    tenant: 'jci',
    site: 'JCI',
  },
  {
    label: 'AdventHealth',
    host: 'adventhealth.wd12.myworkdayjobs.com',
    tenant: 'adventhealth',
    site: 'AH_External_Career_Site',
  },
  {
    label: 'Olathe KS',
    host: 'olatheks.wd1.myworkdayjobs.com',
    tenant: 'olatheks',
    site: 'OlatheKS',
  },
  {
    label: 'Salesforce',
    host: 'salesforce.wd12.myworkdayjobs.com',
    tenant: 'salesforce',
    site: 'External_Career_Site',
  },
  {
    label: 'Deluxe',
    host: 'deluxe.wd5.myworkdayjobs.com',
    tenant: 'deluxe',
    site: 'USA_CAN',
  },
  {
    label: 'Oakland County',
    host: 'oakgov.wd5.myworkdayjobs.com',
    tenant: 'oakgov',
    site: 'careers',
  },
  {
    label: 'Las Vegas Valley Water District',
    host: 'lvvwd.wd1.myworkdayjobs.com',
    tenant: 'lvvwd',
    site: 'LVVWDWaterJobs',
  },
  {
    label: 'Adient',
    host: 'adient.wd3.myworkdayjobs.com',
    tenant: 'adient',
    site: 'External',
  },
];
